# You can use keys for your environments(development, test and production) or you can specify 
# keys for specific domain names(e.g. www.mydomain.org, testing.localhost). If a key is supplied for the domain that 
# corresponds to your current domain it will honored over environment keys.

development:
 ABQIAAAA8U5rsnlRrtQHAp3dBmrdfRTJQa0g3IQ9GZqIMmInSLzwtGDKaBTLlYGbP0X-LAEz_1-9rI9kL_Z0ZQ
test:
 ABQIAAAA8U5rsnlRrtQHAp3dBmrdfRTJQa0g3IQ9GZqIMmInSLzwtGDKaBTLlYGbP0X-LAEz_1-9rI9kL_Z0ZQ
production:
  put_your_production_key_here